# this is a toml 

title = "soapffz's myman config"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "123456"
dbname = "bounty"

[nuclei]
nuclei_poc_dir_path = "/root/toolkit/myown-nuclei-poc"

[serverJ]
serverJkey = "xxxxxxxxxxxxxxxxx"